### PR TITLE
Add Github Actions

### PR DESCRIPTION
**Pull request by 5jiji**
This pull request add a single github actions script to automatically, on every commit push and every pull request tries to build the submitted code.

This would allow to check that the code is, at the minimum, compiling correctly for every single pull request.

If you want, i can also add some building for linux at any point in time.

just so you know, you'll need to add 3 secrets to this repository, if you want, i can set them.

Those secret are:
UNITY_EMAIL: your unity account e-mail
UNITY_PASSWORD: your unity account password
UNITY_LICENSE: a specific file needed specifying the licence

### CODE REVIEW

**Comment by doodlechaos** [comment]
Requiring that the pull request compiles correctly at a bare minimum is a great idea. I have never set github secrets before. If you can use yours that works for me too. Are you sure that on an open source repo the secrets will remain private for you?

**Comment by 5jiji** [comment]
There *are* ways to get the secrets, but that is the reason i made a second unity account and used that
if you really want to, i can share those secrets, as i made it JUST for this project

**Comment by doodlechaos** [comment]
Oh that would be perfect! I, of course, will never intentionally share anything. Let me know if you're able to access the secrets of the repo or if you need extra permissions

**Comment by 5jiji** [comment]
Being that secrets are made by github themselves i think i need write permission in the repository, but i may be wrong

**Pull request merged**
